<a href="https://colab.research.google.com/github/Veera-Divya/LogicMojo-AI-ML-April26-Divya1280/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
print(np.ones([3,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.full([3,4], 6))

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [ ]:
print(np.arange(1, 6, -1))

[]


In [ ]:
print(np.arange(1, 6, 2))

[1 3 5]


In [ ]:
print(np.arange(1, 6))

[1 2 3 4 5]


In [ ]:
np.linspace(1,10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0,1, 12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape([2,4]))

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8, 9, 10, 11, 12])
print(arr.reshape([3,4]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8, 9, 10, 11, 12])
a = arr.reshape([3,2, -1])
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8, 9, 10, 11, 12])
a = arr.reshape([3,2, -1])
print(a)
print(a.flatten())

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8, 9, 10, 11, 12])
a = arr.reshape([3,2, -1])
print(a.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
import numpy as np
arr = np.array([1,2,12, 3,4,5,6,7,8, 9, 10, 11])
a = arr.reshape([3, -1])
print(a)

[[ 1  2 12  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(np.sort(a))
print(a)

[[ 1  2  3 12]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2 12  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(a[0:2, 2:3])

[[12]
 [ 6]]


In [ ]:
print(a[a%3==0])

[12  3  6  9]


In [ ]:
import numpy as np
arr = np.array([1,2,12, 3,4,5,6,7,8, 9, 10, 11])
a = arr.reshape([3, -1])
print(a[a!=0])

[ 1  2 12  3  4  5  6  7  8  9 10 11]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([5,6,7,8,9,9])
print(np.add(a, b))
print(a+b)



[ 6  8 10 12 14 15]
[ 6  8 10 12 14 15]


In [ ]:
c=np.array([3,4,5,6])
print(a+c)

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [ ]:
# broadcasting
a=np.array([5,6,7,8])
b=1
print(a+b)


[6 7 8 9]


In [ ]:
# broadcasting
a=np.array([1,2,3])
b=np.array([[2,3,4], [4,5,6]])
print(a+b)

[[3 5 7]
 [5 7 9]]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([[2,3,4], [4,5,6]])
print(a+b)

ValueError: operands could not be broadcast together with shapes (4,) (2,3) 

In [ ]:
a=np.array([1,2,3])
b=np.array([[2,3,4], [4,5,6]])
print(a+b)
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[3 5 7]
 [5 7 9]]
[[-1 -1 -1]
 [-3 -3 -3]]
[[ 2  6 12]
 [ 4 10 18]]
[[0.5        0.66666667 0.75      ]
 [0.25       0.4        0.5       ]]


In [ ]:
print(np.mean(b))

4.0


In [ ]:
print(np.minimum(a, b))

[[1 2 3]
 [1 2 3]]


In [ ]:
print(np.minimum(3, 4))

3


In [ ]:
print(np.maximum(a, b))

[[2 3 4]
 [4 5 6]]


In [ ]:
print(np.std(b, dtype = np.float32))
print(np.std(b, dtype = np.float64))
print(np.std(b))

1.2909944
1.2909944487358056
1.2909944487358056


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([5,6,7,8,9,9])
b= b.reshape(2,3)
print(b)
print(b.T)

[[5 6 7]
 [8 9 9]]
[[5 8]
 [6 9]
 [7 9]]


In [ ]:
a = np.array([1,2,3,4,5,6])
b = np.array([5,6,7,8,9,9])
b= b.reshape(2,3)
a=a.reshape(2,3)
print(a)
print(b)
print("Concatinate along rows ", np.concatenate((a,b), axis = 0))
print("Concatinate along cols ", np.concatenate((a,b), axis = 1))

[[1 2 3]
 [4 5 6]]
[[5 6 7]
 [8 9 9]]
Concatinate along rows  [[1 2 3]
 [4 5 6]
 [5 6 7]
 [8 9 9]]
Concatinate along cols  [[1 2 3 5 6 7]
 [4 5 6 8 9 9]]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([5,6,7,8,9,9])
b= b.reshape(2,3)
a=a.reshape(2,3)
print(np.split(a, 2))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([5,6,7,8,9,9])
b= b.reshape(2,3)
a=a.reshape(2,3)
print(np.vstack((a, b)))
print(np.hstack((a, b)))
print(np.stack((a, b)))

[[1 2 3]
 [4 5 6]
 [5 6 7]
 [8 9 9]]
[[1 2 3 5 6 7]
 [4 5 6 8 9 9]]
[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 9]]]
