<a href="https://colab.research.google.com/github/Veera-Divya/LogicMojo-AI-ML-April26-Divya1280/blob/main/numpy_assignments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2, -1)
print("a :", a)
print("b :", b)
print(np.vstack([a,b]))
print(np.concatenate([a,b], axis = 0))

a : [[0 1 2 3 4]
 [5 6 7 8 9]]
b : [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
### reverse an array
arr = np.array([1,2,3,4,5,6])
print(arr[::-1])

[6 5 4 3 2 1]


In [ ]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])

a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[(a>5) & (a<10)])


[6 9]


In [ ]:
# Find the maximum value from both of these array

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
print(max(max(a), max(b)))

9
