<a href="https://colab.research.google.com/github/Veera-Divya/LogicMojo-AI-ML-April26-Divya1280/blob/main/numpy_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
# 32-> scalar -0 dim
# [1,2,3] -> 1 dim
# [[1,2,3], [1,2]] -> 2dim
arr = np.array(34)
print(arr.ndim)
arr = np.array([1,2,3])
print(arr.ndim)
arr = np.array([[[[]]]])
print(arr.ndim)

0
1
4


In [12]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [19]:
arr = np.arange(0, 1, 0.5)
arr

array([0. , 0.5])

In [16]:
arr = np.arange(20, 10, -2)
arr

array([20, 18, 16, 14, 12])

In [21]:
# to create evenly space numbers between two numbers
arr = np.linspace(0, 1, 10) # start stop number of values
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
#logariithmic scale array
arr = np.logspace(1, 3, 3) #startingpower #ending power #number of values (how evenly spaced)
arr


array([  10.,  100., 1000.])

In [24]:
#logariithmic scale array
arr = np.logspace(1, 3, 2) #startingpower #ending power #number of values
arr

array([  10., 1000.])

In [25]:
#logariithmic scale array
arr = np.logspace(1, 3, 1) #startingpower #ending power #number of values
arr

array([10.])

In [26]:
#logariithmic scale array
arr = np.logspace(1, 3, 4) #startingpower #ending power #number of values (how evenly spaced)
arr

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [27]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
arr = np.ones([1,4,5], dtype=int) #by default it will be float
arr

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [33]:
arr = np.full(10, 5) # create any array of full of any value
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [37]:
arr = np.full([2,4], 't') # create any array of full of any value
arr

array([['t', 't', 't', 't'],
       ['t', 't', 't', 't']], dtype='<U1')

In [40]:
arr = np.empty(5) #uninitialzied array-> create an array without setting any values
arr

array([0., 0., 0., 0., 0.])

In [42]:
arr = np.empty([1,2]) #uninitialzied array-> create an array without setting any values
arr

array([[  10., 1000.]])

In [43]:
np.random.rand() #random floats(0 to 1)

0.4086990531623915

In [44]:
np.random.rand(2) #random floats(0 to 1), #param - is number of floats

array([0.94884167, 0.26286522])

In [45]:
np.random.rand(2, 3) #random floats(0 to 1), #param - is number of floats

array([[0.53128745, 0.26634613, 0.92562816],
       [0.61450579, 0.69838648, 0.30574203]])

In [48]:
np.random.randn(2, 3) #random floats from standard normal distibution


array([[ 0.47110038,  0.4117797 ,  0.11664203],
       [ 0.79301377,  0.40345775, -0.19695135]])

In [61]:
arr = np.random.randint(4) #-> random integers range is given
arr

3

In [52]:
np.random.randn() #random floats from standard normal distibution

-0.13091383196171563

In [57]:
arr = np.random.randint(10, 100) #-> random integers *range
arr

31

In [62]:
arr = np.random.randint() #-> random integers

TypeError: randint() takes at least 1 positional argument (0 given)

In [67]:
arr = np.random.randint(10, 14, size=(2,3)) #-> random integers (start, stop, dim)
arr

array([[12, 11, 13],
       [10, 11, 13]])

Numoy Data types and Type Casting

In [68]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [69]:
print(type(arr))

<class 'numpy.ndarray'>


In [71]:
list = ["string", 1, 2,3]
arr = np.array(list)
print(arr)
print(arr.dtype)

['string' '1' '2' '3']
<U21


In [72]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [74]:
arr = np.array([1,2,3,4], dtype=np.float32)
arr.dtype

dtype('float32')

In [75]:
arr

array([1., 2., 3., 4.], dtype=float32)

In [76]:
arr = np.array([1.2, 1.3], dtype=np.int64) # removes the decimal
arr

array([1, 1])

In [77]:
arr = np.array([1,2,3.1, 4, 5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

**TypeCasting**

In [80]:
arr = np.array([1,2,3,4])
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3., 4.])

In [81]:
new_arr2= new_arr.astype(np.int64)
new_arr2

array([1, 2, 3, 4])

In [82]:
#Type casting errors
arr = np.array([1, 2, "Hello"])
new_arr = arr.astype(np.int64)

ValueError: invalid literal for int() with base 10: np.str_('Hello')

In [83]:
arr = np.array([[1,2,3], [5,6,7]])
arr.ndim


2

In [84]:
arr.shape

(2, 3)

In [85]:
arr.size

6

In [86]:
arr.itemsize #check the each element size in array in bytes

8

Array Reshaping -> Reshape, Ravel, flatten

In [89]:
arr = np.arange(1,10)
new_arr= arr.reshape(3,3)
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
# ravel -> convert the array to 1 D array
# return a view  of original array which basically means any changes you apply here reflected in original array
new_arr2= np.ravel(new_arr)
print(new_arr2)
new_arr2[0] = 1
print(new_arr)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [99]:
# flaten -convert the array to 1 D array
# return the copy of array
flat = new_arr.flatten()
print(flat)
flat[0] = 0
print(new_arr)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Arithmetic Opeartions**

In [100]:
a = np.array([1,2,3,4])
b= np.array([5,6,7,8])
print(a+b)

[ 6  8 10 12]


In [101]:
#subtraction
print(a-b)

[-4 -4 -4 -4]


In [102]:
#division
print(a/b)


[0.2        0.33333333 0.42857143 0.5       ]


In [103]:
#multiplication
print(a*b)

[ 5 12 21 32]


In [107]:
# integer division
print(a//b)
print(b//a)

#normal division
print(b/a)

[0 0 0 0]
[5 3 2 2]
[5.         3.         2.33333333 2.        ]


In [109]:
#modulous
print(a%b)
print(b%a)

[1 2 3 4]
[0 0 1 0]


In [110]:
#exponent
print(a**2)

[ 1  4  9 16]


UNIVERSAL FUNCTIONS - ufuncs

In [112]:
arr = np.array([1, 4, 9, 16])


In [113]:
# square root
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [116]:
#exponential
print(np.exp([arr]))

[[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]]


In [117]:
#sine function
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


INDEXING AND SLICING

In [118]:
arr = np.array([1,2,3,4])
print(arr[0])

1


In [119]:
arr[::2]

array([1, 3])

In [121]:
print(arr[-1])

4


In [123]:
arr = np.array([[2,2,4,5], [5,6,7,8,]])
arr

array([[2, 2, 4, 5],
       [5, 6, 7, 8]])

In [124]:
arr[0:2, 0:1]

array([[2],
       [5]])

In [127]:
arr[0:2, [1,2]]

array([[2, 4],
       [6, 7]])

Index Arrays


In [128]:
arr = np.array([1,2,3,4,5,6])
ind = [0,2]
print(np.take(arr, ind))

[1 3]


In [129]:
# Iterating  with nditer()
arr = np.array([[1,2,3], [4,5,6]])
for x in np.nditer(arr):
  print(x, end=" ")

1 2 3 4 5 6 

In [131]:
# Iterating  with ndenumerate
arr = np.array([[1,2,3], [4,5,6]])
for i, x in np.ndenumerate(arr):
  print(i, x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [132]:
# Views vs Copies

#view
arr = np.array([1,2,4,5,6])
view = arr[1:3]
view[0] = 200
print(arr)

[  1 200   4   5   6]


In [133]:
#copy
arr = np.array([1,2,4,5,6])
copy = arr[1:3].copy()
copy[0] = 200
print(arr)

[1 2 4 5 6]


In [137]:
# Transpose
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.T)
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [140]:
# swapaxes -> swap 2 specific axes in a matrix
swap = np.swapaxes(arr, 0, 1)
print(swap)
swap.shape

[[1 4]
 [2 5]
 [3 6]]


(3, 2)

In [145]:
#concatenaate
a = np.array([1,2,3, 4])
b= np.array([4,5,6,7])
c= np.concatenate([a,b], axis = 0)
print(c)

[1 2 3 4 4 5 6 7]


In [147]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.concatenate([a,b], axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [152]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.concatenate((a,b), axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [151]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.vstack((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [153]:
np.stack((a,b))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [157]:
np.stack((a,b), axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [158]:
# splitting Arrays
arr = np.array([[1,2], [3,4], [5,6], [7,8]])
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [161]:
print(np.split(arr, 2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [162]:
print(np.split(arr, 3))

ValueError: array split does not result in an equal division

In [163]:
print(np.hsplit(arr, 2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [164]:
print(np.vsplit(arr, 2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [166]:
# Repeating each element
arr = np.array([1,2,3])
print(np.repeat(arr, 3))

[1 1 1 2 2 2 3 3 3]


In [167]:
# Repeating whole array
arr = np.array([1,2,3])
print(np.tile(arr, 3))

[1 2 3 1 2 3 1 2 3]


In [175]:
#Aggregate functions
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))








6
2.0
2.0
0.816496580927726
0.6666666666666666
3
1


In [176]:
arr = np.array([[1,2,3], [4,5,6]])
print(np.sum(arr, axis=0))

[5 7 9]


In [177]:
print(np.sum(arr, axis=1))

[ 6 15]


In [180]:
print(np.cumsum(arr))

[ 1  3  6 10 15 21]


In [182]:
#where
arr = np.array([1,2,3])
result = np.where(arr<2, "low", "high")
print(result)

['low' 'high' 'high']


In [185]:
#argswhere # retunr index list
print(np.argwhere(arr>1))

[[1]
 [2]]


In [188]:
print(np.argwhere(arr>4))

[]


In [187]:
mask = np.logical_and(arr>15, arr<35)
print(mask)

[False False False]


In [189]:
arr = np.array([[1,2,3], [1,5,6]])
mask = np.logical_and(arr>15, arr<35)
print(mask)

[[False False False]
 [False False False]]
