<a href="https://colab.research.google.com/github/Veera-Divya/LogicMojo-AI-ML-April26-Divya1280/blob/main/numpy_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
# 32-> scalar -0 dim
# [1,2,3] -> 1 dim
# [[1,2,3], [1,2]] -> 2dim
arr = np.array(34)
print(arr.ndim)
arr = np.array([1,2,3])
print(arr.ndim)
arr = np.array([[[[]]]])
print(arr.ndim)

0
1
4


In [12]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [19]:
arr = np.arange(0, 1, 0.5)
arr

array([0. , 0.5])

In [16]:
arr = np.arange(20, 10, -2)
arr

array([20, 18, 16, 14, 12])

In [21]:
# to create evenly space numbers between two numbers
arr = np.linspace(0, 1, 10) # start stop number of values
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
#logariithmic scale array
arr = np.logspace(1, 3, 3) #startingpower #ending power #number of values (how evenly spaced)
arr


array([  10.,  100., 1000.])

In [24]:
#logariithmic scale array
arr = np.logspace(1, 3, 2) #startingpower #ending power #number of values
arr

array([  10., 1000.])

In [25]:
#logariithmic scale array
arr = np.logspace(1, 3, 1) #startingpower #ending power #number of values
arr

array([10.])

In [26]:
#logariithmic scale array
arr = np.logspace(1, 3, 4) #startingpower #ending power #number of values (how evenly spaced)
arr

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [27]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr